# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b09190359820922bf28dbe9dd2d766158c45fa423349524c851d9e2de3f81152bcdf3b0b1a64f0a555d47f9fb67ca0c03573ba10dedc35da67651d91c0a42555

test:
  secret_key_base: a0d63097b675c36cd2fe23a8a5f303122307d94067e0c071a259303824a48f6bff5d4a1af580c436fbab5d83799d3d508f65558fc9dab4d0bf858a709cd9a3a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
